name: sort-uniq
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: check sort and uniq
      run: "./${{ github.action_path }}/scripts/workflows/sort-uniq.sh"
      shell: bash