name: lint

on:
  push:
    branches:
      - main
    paths:
      - 'orgs-data/**'
      - '.github/workflows/*'
  pull_request:
    paths:
      - 'orgs-data/**'
      - '.github/workflows/*'
  workflow_dispatch:

permissions: read-all

jobs:
  tabs:
    runs-on: ubuntu-latest
    steps:
      - uses: nikitastupin/orgs-data/actions/tabs@main

  sort-uniq:
    runs-on: ubuntu-latest
    steps:
      - uses: nikitastupin/orgs-data/actions/sort-uniq@main

  columns-and-content:
    runs-on: ubuntu-latest
    steps:
      - uses: nikitastupin/orgs-data/actions/columns-and-content@main

  forget-nothing:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: nikitastupin/orgs-data/actions/forget-nothing@main
